name: build_switch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        preset: [switch]
    runs-on: ${{ matrix.os }}
    container: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v3

    # fetch latest cmake
    - uses: lukka/get-cmake@latest

    - name: Configure CMake
      # disable ftp-gc until dkpa64 container uses latest libnx
      run: |
        cmake --preset ${{ matrix.preset }} -DUSE_VFS_GC=0

    - name: Build
      run: |
        cmake --build --preset ${{ matrix.preset }} --parallel 4
        mkdir -p dist/sysmod/atmosphere/contents
        mkdir -p dist/sysmod/config/ftpsrv
        cp assets/config.ini.template dist/sysmod/config/ftpsrv/config.ini.template
        cp -r build/switch/420000000000011B dist/sysmod/atmosphere/contents
        pushd dist/sysmod/
        zip -r9 ../ftpsrv_sysmod.zip *
        popd


    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist
